version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb_dev
    ports:
      - "5433:5432"
    environment:

      POSTGRES_DB: financial_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data: